version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "document-service"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-qd51n5t275i2"
s3_prefix = "document-service"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "NetworkStackNameParameter=\"coffeeshop-2020-7\""
