AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-lambda-python-microservice

  Sample SAM Template for aws-lambda-python-microservice

Parameters:
  NetworkStackNameParameter:
    Type: String
    Description: Enter network stack name

Globals:
  Function:
    Timeout: 20

Resources:

  DataBucket:
    Type: AWS::S3::Bucket

  DocumentLambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Redis + Lambda on SAM Security Group"
      VpcId:
        Fn::ImportValue:
          Fn::Sub: "${NetworkStackNameParameter}-VPC"
      SecurityGroupEgress:
        - CidrIp: "0.0.0.0/0"
          FromPort: 0
          ToPort: 65535
          IpProtocol: tcp
      SecurityGroupIngress:
        - CidrIp: "0.0.0.0/0"
          FromPort: 0
          ToPort: 65535
          IpProtocol: tcp

  DocumentServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref DataBucket
        - SSMParameterReadPolicy:
            ParameterName: "/document/s3/data-bucket/S3bucket"
      VpcConfig:
        SecurityGroupIds:
          - !Ref DocumentLambdaSecurityGroup
        SubnetIds:
          - Fn::ImportValue:
              Fn::Sub: "${NetworkStackNameParameter}-PublicSubnet1"
          - Fn::ImportValue:
              Fn::Sub: "${NetworkStackNameParameter}-PublicSubnet2"
      Events:
        GetDocument:
          Type: Api
          Properties:
            Path: /document
            Method: get

  DataBucketName:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: "/document/s3/data-bucket/S3bucket"
      Type: "String"
      Value: !Ref DataBucket
      Description: "S3 Data Bucket Name"

Outputs:
  HelloDocumentApi:
    Description: "API Gateway endpoint URL for Prod stage for Document function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/document/"
