version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: my_postgres_container
    environment:
      POSTGRES_USER: test 
      POSTGRES_PASSWORD: password
      POSTGRES_DB: coffee_order
    ports:
      - "5432:5432"
