AWSTemplateFormatVersion: 2010-09-09
Description: >-
  asynchronous service to service communication

Transform:
- AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 25 # Chosen to be less than the default SQS Visibility Timeout of 30 seconds

Resources:

  CustomerPaymentServiceQueue:
    Type: AWS::SQS::Queue

  # This is the Lambda function definition associated with the source code: paymentService.js. For all available properties, see
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  StripePaymentFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs12.x
      Handler: ../aws-lambda-node-microservice/payment-proxy-service/src/handlers/paymentService.handler
      Events:
        CustomerPaymentJobQueue:
          Type: SQS
          Properties:
            Queue: Fn::GetAtt CustomerPaymentServiceQueue.Arn
            BatchSize: 1
      MemorySize: 128
      Policies:
        - AWSLambdaBasicExecutionRole
        - SQSPollerPolicy: # https://github.com/awslabs/serverless-application-model/blob/develop/samtranslator/policy_templates_data/policy_templates.json
            QueueName: !Ref CustomerAccountingServiceQueue
